### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by bserem** [suidroot/TimeWarriorGUI#4]
I can't figure out how to use this. I added it in the extensions folder and made it executable:
```
$ timew extensions 

Extensions located in:
  /home/bserem/.timewarrior/extensions

Extension Status
tw-gui.py Active
```

Any hints would be most welcome!
Thanks

**Comment by suidroot** [comment]
This is a standalone script, not a Timewarrior plugin. You can run the script directly using python

`python tw-gui.py`

The UI should then open.

**Comment by bserem** [comment]
Thanks

PR: https://github.com/suidroot/TimeWarriorGUI/pull/5
To see how it looks like: https://github.com/bserem/TimeWarriorGUI/tree/patch-1
Hope you like!

**Comment by suidroot** [comment]
Looks great thanks for submitting the update
